[package]
name = "uptime"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yml = "0.0.11"
serde_json = "1.0"

actix-web = "4"

rusqlite = "0.33.0"
